name: DoubleJumpReload
main: com.github.luksdlt92.DoubleJumpReload
version: 1
commands:
  djdelay:
    description: Saber cantidad de jugadores con cooldown.
    usage: /<command>
  djclear:
    description: Limpiar cooldown.
    usage: /<command>
  djtoggle:
    description: Activa / Desactiva el Double Jump.
    usage: /<command>