name: DoubleJumpReload
main: com.github.luksdlt92.DoubleJumpReload
version: 1
commands:
  doublejumpdelay:
    description: Saber cantidad de jugadores con cooldown.
    usage: /<command>
  doublejumpclear:
    description: Limpiar cooldown.
    usage: /<command>